### PR TITLE
feat: support `@value` at-rule in selectors

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Support `@value` at rule in selectors

### Breaking Changes

Yes

BREAKING CHANGE: if you have name of `@value` in selector it will be replaced, you need to rename your name of `@value` or rename your selector

### Additional Info

No

For next major release we need:
- fix `nothing` in test of css-loader
- fix problem when you use `@value test: 'something'` in selector
- refactor postcss-icss plugin

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Is there any way to disable this feature?

**Comment by evilebottnawi** [comment]
@Hypnosphi no, just rename your variable to `v-myClass`

> I use the following pattern a lot, so now I need a large refactoring to make it work again

It is breaking change for `css-loader@3`, so it is normal when you need refactor

**Comment by Hypnosphi** [comment]
> rename your variable to `v-myClass`

That would mean that in `some/other.js` i would have to use something like `styles['v-myClass']` which looks suboptimal comparing to `styles.myClass`

**Comment by evilebottnawi** [comment]
@Hypnosphi just use other class or change variable name, it can't be opt, sorry

**Comment by princed** [comment]
@evilebottnawi Would you accept a PR making it possible to opt-out? In our project, we'd have to update about 5000 lines because of the feature.

**Comment by evilebottnawi** [comment]
@princed it can be options, postcss plugins were rewritten

**Pull request merged**
