### PR TITLE
feat: use template literal when it possible to prevent `Maximum call …

### PR DESCRIPTION
**Pull request by alexander-akait**
…stack size exceeded`

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

fixes https://github.com/webpack-contrib/css-loader/issues/771

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Review by sgarfinkel — APPROVED** [review]
LGTM

**Comment by sgarfinkel** [comment]
Could possibly infer this from browserslist?

**Comment by alexander-akait** [comment]
@sgarfinkel We already do it on webpack side level https://webpack.js.org/configuration/target/, so if you have `browserslist` we will use it

**Comment by alexander-akait** [comment]
> Infer a platform and the ES-features from a browserslist-config (default if browserslist config is available)

**Pull request merged**
