### PR TITLE
docs(README): add server-side rendering (SSR) example

### PR DESCRIPTION
**Pull request by BurkovBA**
**What kind of change does this PR introduce?**
Added documentation of server-side rendering `css-loader` setup to README.md

**Did you add tests for your changes?**
Not applicable

**If relevant, did you update the README?**
Yes

**Summary**
This PR is [based on my experience](https://github.com/webpack-contrib/css-loader/issues/676#issuecomment-365589522), building a bundle for server-side rendering.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by BurkovBA** [comment]
@michael-ciniawsky 

Hi, Michael, thanks for review. Yes, I'm not 100% sure about the scope, too. 

On the other hand, it might make sense to provide an example of using `css-loader` in server-side environment.

Maybe, It is too verbose now? I'll try to shorten it.

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Maybe move documentation in `webpack` docs and just put link with small description in readme?

**Comment by michael-ciniawsky** [comment]
@BurkovBA Yep, it is to 'verbose' in the sense that it's more an SSR guide in general with a specific solution unrelated to `css-loader` in many ways (`webpack` config, `webpack-node-externals` etc). This projects README focuses on the loader itself (`options` etc) without too much integration docs for different setups. Not to criticise the guide in general, but it would need to be a link to a guide like this then, to aviod bloating the README to much

**Comment by michael-ciniawsky** [comment]
or a blog post in the sense of 'guide'

**Comment by BurkovBA** [comment]
@michael-ciniawsky , @evilebottnawi 

Updated the PR.

I dropped everything non-CSS related. Also made it concise and less like a guide and more like a documentation.

**Comment by evilebottnawi** [comment]
@BurkovBA sorry for delay, can you rebase your PR and use `mini-css-extract-plugin` plugin in example

**Comment by evilebottnawi** [comment]
After investigate i think it is real out of scope of `css-loader`, better create issue in `webpack` docs repo and writing page about SSR, because it is require additional setup not only for `css-loader`. Anyway thanks for the PR.

**Pull request closed without merging**
