### PR TITLE
Enable getLocalIdent in global options

### PR DESCRIPTION
**Pull request by hh9527**
**What kind of change does this PR introduce?**

This PR will enable global options, and thus can give a workaround to https://github.com/webpack/css-loader/issues/389 : just put getLocalIdent in global options via LoaderOptionsPlugin

**Did you add tests for your changes?**

Yes, in my project, I use a patch to this loader, and works fine.

**If relevant, did you update the README?**

Not yet. cause it still has space to improve: enable other options in global. but it should be judged by project owner.

**Summary**

See above.

https://github.com/webpack/css-loader/issues/389

**Does this PR introduce a breaking change?**

No

**Other information**

This will make it possible to work with webpack2 and extract-text-webpack-plugin

### CODE REVIEW

**Comment by gustavohenke** [comment]
> Did you add tests for your changes?
> 
> Yes, in my project, I use a patch to this loader, and works fine.

Duh, "tests" are meant to be unit tests.

**Comment by timse** [comment]
I think what you are trying to fix can be solved by adding "ident" to you loaders options. (which may or may not be automatic soon :)).

**Comment by michael-ciniawsky** [comment]
> I think what you are trying to fix can be solved by adding "ident" to you loaders options.

@timse can you confirm this ? :)

**Comment by michael-ciniawsky** [comment]
See reply #389, this should be fixed now :) thx

**Pull request closed without merging**
