### PR TITLE
Fix inline loader syntax in import

### PR DESCRIPTION
**Pull request by alexander-akait**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fixes #1270

### Breaking Changes

No

### Additional Info

More tests + update deps

### CODE REVIEW

**Comment by jquense** [comment]
this is working great thanks! Any ideas for solving the `auto` behavior when the request path differs from the virtual resource path?

**Comment by alexander-akait** [comment]
@jquense Can you clarify what is not working? Based on my tests, all works fine...

**Comment by jquense** [comment]
Cases like the original issue:

`import styles from 'Button.module.css!=!./not-modules.css'`

Or

`import styles from 'Button.module.css!=!base64-loader?data=[base64 string]!./button.js'`

Or just

`import styles from 'Button.module.css!=!base64-loader?data=[base64 string]'`


The first 2 compile but don't return modules, the last one doesn't breaks loudly

**Comment by alexander-akait** [comment]
> The first 2 compile but don't return modules

What do you mean, can you provide example?

**Comment by jquense** [comment]
yes here are two test cases: https://github.com/webpack-contrib/css-loader/pull/1273/files I would expect both cases to be processed as css modules

**Pull request merged**
