### PR TITLE
use absolute paths and remove sourceRoot when generating sourcemaps

### LINKED ISSUE #373: Problem with hard-coded sourceRoot
I'm using css-loader (with sass-loader), and I'm finding that CSS source maps are not working in Chrome or Firefox. The generated CSS is being dynamically inserted by style-loader, and in the Chrome developer tools Styles panel, all of the source links look like this:

    blob:http://localhost:8080/022723dd-255f-4c67-8da3-486c82cba226

When clicked, these links take me to the generated CSS and not the original source SCSS file.

It seems as if this problem is related to the hard-coded sourceRoot being set by css-loader (https://github.com/webpack/css-loader/blob/master/lib/loader.js#L106):

    map.sourceRoot = "webpack://";

Chrome doesn't seem to know how to interpret this and find the source files, and I can't see any way to override this sourceRoot, so I tried temporarily changing that line of code to this:

    map.sourceRoot = "http://localhost:8080";

...and the source maps started working. Am I missing something or is this a problem with css-loader?

### PR DESCRIPTION
**Pull request by brokenmass**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
Yes

**If relevant, did you update the README?**
Not relevant

**Summary**
Simplifies and correct sourcemaps generation by returning absolute sources paths and removing sourceRoot.
Fix #373 and #280

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by brokenmass** [comment]
any updates ?

**Comment by d3viant0ne** [comment]
@brokenmass for reference ping  `@webpack-contrib/org-maintainers` as it's easy to miss comments in the news feed and watching 43 repositories is a nightmare :)

**Comment by jasisk** [comment]
This change appears to introduce some complexity for using, e.g., chrome dev tools.

Because `css-loader` is no longer following the same convention as webpack's source mapping, you end up having to add multiple workspace mappings. I presently store my css alongside the component it corresponds to. I could not figure out the exact incantation of mappings to get everything to work.

Additionally, without a protocol, Chrome treats the path as an absolute path _after_ the host. So, on a Mac, it resolves to `http://something.website:port/Users/myUserName/...`.

**Comment by d3viant0ne** [comment]
@jasisk - Can you get this into a new issue so we are sure this can be addressed one way or another

**Comment by michael-ciniawsky** [comment]
Yep please open a new issues this is a very inconvenient regression to said it politely, we need to investigate in a clean way 😛

**Comment by davicho** [comment]
I find paths absolute slightly inconvenient. As I inspect my css in the dev tools.... the path can be so long it truncates the actual file name - making have to leave my work are to hover of the path and get the tooltip to see the actual file name I need to work on. (Unless, there is an option to undo this but I have looked and have not seen such). Ty.
truncated-path

**Pull request merged**
