### PR TITLE
feat: resolve issue #1028: optimising naming for best compression

### PR DESCRIPTION
**Pull request by denisx**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

resolve issue #1028 

For efficient gzip/br compression, plugin combine css hash via one symbol name,
as a classname position at file, with filepath `hash:base64:8`, to have strong sequences.

### CODE REVIEW

**Comment by denisx** [comment]
have some bugs from master :/ 
npm audit fix change pakage-lock.json ...

**Comment by joseprio** [comment]
We use a similar technique, but just defining a custom `getLocalIdent`. However, I don't think this plays well with the caching mechanism, as the classname generation isn't stable, right?

**Comment by denisx** [comment]
@joseprio 
> However, I don't think this plays well with the caching mechanism, as the classname generation isn't stable, right?
Css-loader get async files and parse, it is allways randomized work. Class save classnames positions for every file (a,b,c,...). As a file-path, it is always stable content hash for project. It is cache frendly.

**Comment by denisx** [comment]
and https://gist.github.com/denisx/9dc0e8c542b810e67f41691c89e7b948 for check hash length

**Comment by denisx** [comment]
Add css hash len suggest - we have full hash map after css-1-letter running.

**Pull request closed without merging**
