### PR TITLE
docs(README): add note about hash collision problem

### PR DESCRIPTION
**Pull request by user1736**
**What kind of change does this PR introduce?**
Added documentation about hash collision problem described [here](https://github.com/webpack-contrib/css-loader/issues/413)

**Did you add tests for your changes?**
Not applicable

**If relevant, did you update the README?**
Yes

**Summary**
I decided to document workaround from discussion in https://github.com/webpack-contrib/css-loader/issues/413 to make people more aware of that problem

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by user1736** [comment]
Is anybody alive there? It'll be nice to have it triaged at least

**Comment by evilebottnawi** [comment]
@user1736 can you provide example with hash collision?

**Comment by evilebottnawi** [comment]
Maybe we can fix it on our side without documentation

**Comment by user1736** [comment]
@evilebottnawi did you check the conversation in https://github.com/webpack-contrib/css-loader/issues/413? This is what I'm talking about

**Comment by evilebottnawi** [comment]
@user1736 yes, not reproducible test repo, if you provide we can fix it in next major release (will be released in near future)

**Comment by user1736** [comment]
@evilebottnawi, sorry, but did I miss something? https://github.com/webpack-contrib/css-loader/issues/413#issuecomment-365926350 you said that documentation is welcome and the issue labeled with doc tag.

If documentation not needed anymore feel free to close this PR. I'll consider creating test repo for that problem then.

**Comment by evilebottnawi** [comment]
@user1736 we should first look on reproducible repo, if it is won't fix we documented this

**Comment by ScriptedAlchemy** [comment]
Agreed, Ive seen collisions before. This was way back in Webpack 1. I believe someone on my team pached this waaaay back. 

We need to reproduce this with a repo to help

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy because we use salt and very long key for hashing and problem with colussion right now should don't exists

**Comment by ScriptedAlchemy** [comment]
@evilebottnawi Agreed, I watched your team move to the better hashing / my team was involved a long time ago in solving similar issues in webpack hashing. 


There should not be any collisions based on my experience with webpack hashing functions. 

Again, we need a repo to help @user1736 and are more than willing to do so. But we **must** understand and see the issue to trace the problem.

**Comment by evilebottnawi** [comment]
Can't reproduce so it is not actually, anyway feel free to open an issue/a PR if you faced with bug

**Pull request closed without merging**
