### PR TITLE
Init `minimizeOptions` should be `query.minimize`!

### PR DESCRIPTION
**Pull request by JounQin**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No

**If relevant, did you update the README?**
No need

**Summary**
It's a mistake according to the doc.

Init `minimizeOptions` should be `query.minimize` rather than just `query`.

Please review it immediately.

https://github.com/webpack/css-loader#minification

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by bebraw** [comment]
If you could add a test, this would be ready to go in.

**Comment by michael-ciniawsky** [comment]
@JounQin Please close and reopen the PR to trigger the CLA Bot again, should be working now 😛 
And please a a test 👍

**Comment by JounQin** [comment]
@bebraw @michael-ciniawsky 
Hi, all, I've fixed the error of CI test, and `moduleMinimizeTest.js` should have test is already.

**Comment by michael-ciniawsky** [comment]
@JounQin Thx 👍

**Pull request merged**
