### PR TITLE
chore: update dependencies to the latest version

### PR DESCRIPTION
**Pull request by ersachin3112**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
update dependencies to the latest version

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by lhtdesignde** [comment]
@snitin315 @ersachin3112  Would it be possible to make a release with this? It would fix this vulnerability https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
Version `6.8.1` still runs `"semver": "^7.3.8"`

**Comment by evenstensberg** [comment]
CC @alexander-akait

**Comment by alexander-akait** [comment]
@lhtdesignde Hello, what is the problem to update postcss locally? We use `^` so we don't block this action

**Comment by lhtdesignde** [comment]
@alexander-akait not sure what you mean. I have semver version 7.5.4 installed but the version within the node_modules of css-loader is still 7.3.8. 🤷🏻‍♀️ I can't really handle this as semver is not a peer dependency.
But no worries. It's not a critical vulnerability. It can wait till your next release.

**Pull request merged**
