### PR TITLE
test: clearer test case for 966

### PR DESCRIPTION
**Pull request by jquense**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Follow up to #973

### CODE REVIEW

**Comment by jquense** [comment]
Let me try and figure out what is different about this vs my setup @evilebottnawi

**Comment by evilebottnawi** [comment]
I see problem, when you use `localIdentName` we escape all special CSS characters, but when you use `getLocalIdent` we output as returned value without escaping, maybe you are right and it is bug, i think we should use the same logic for both cases

**Comment by evilebottnawi** [comment]
We escape all characters in placeholder excluding `[locals]`

**Comment by jquense** [comment]
AHHHH you're right! That's the problem it assumes that the local name is _already_ css safe. I think it's safe to make that change? Or would it not be ok?

**Comment by evilebottnawi** [comment]
@jquense i think we should always escape non standard CSS character in both cases, why? because you path can contains invalid characters for CSS, `localIdentName` already works as expected, but getLocalIdent - no

**Pull request closed without merging**
