### PR TITLE
docs(readme): adding extract css chunks to REAMDME

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Adding it to the documentation as a alternative / extended version of mini-css-extract. 
Extract css chunks offers hot module reloading while in development, allowing for good performance on the client and build. 
As you guys will know, mini-css is fast, this brings the benefits of it to development without losing the ability to hot reload.

### Breaking Changes

None, just docs

### Additional Info

With great respect, for you consideration.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Ahhh okay, thank you. Ill do so when i get back on my computer. Appreciate it!

**Comment by ScriptedAlchemy** [comment]
hey @evilebottnawi let me know if this is acceptable :) appreciate the patience!

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy need fix CI

**Comment by ScriptedAlchemy** [comment]
i will take over mini-css plugin of webpack would be willing to add me as a member/collaborator. I really really want to get involved with Webpack again

however, till i can properly discuss this with you and your team, i would like the ReadMe updated as i want to work on a smarter solution that may require collaboration between us. 

I used to help you guys out long ago, and my coauther has written requireWeak for you. I want to add value to the overall project and would ask you to take this into consideration. I want to work with people smarter than myself and i hope my unique skills can work teach some new ideas to the team as well.

**Comment by ScriptedAlchemy** [comment]
ill address builds issues today. been mobile for a few days

**Comment by ScriptedAlchemy** [comment]
sorry, took me a few attempts to understand the commitlint. super cool by the way, definitely going to adopt that practice. 

ill gladly help Webpack team maintain anything they need, and I myself am obsessed with performance. along with the ability to allow many builds to act like one.

to offer some value back to webpack and the community would be really great. I have a deep understanding of webpack architecture and my career is built around architecting billion dollar companies platforms. 

I am sure you often get users asking to join, but I believe that my contributions could benefit the project in a positive way. 
Let me know what is required, I would definitely love to move towards being a member of webpack-contrib group, and hopefully - one day. the webpack core

With Universal being merged into React, and React Static 6 released and stable. I'll have more time which to allocate so something I am passionate about - webpack. Whatever maintainers you need, count me in! I am not perfect, but I will give you passion and hard work along with my renowned skills in javascript performance optimization

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Great news! https://webpack.slack.com/messages/C1LUX2DS9/ invite here and write me, when we invite you private channel. We need more contributors, we have a lot of repo and sometimes and we don't have enouth time on all repo, new contributors welcome, also we fund your work!

**Comment by ScriptedAlchemy** [comment]
Oh my gosh! Oh my gosh! Oh my gosh! 

This is a dream come true. I have wanted this moment my whole career. Since webpack 1. 

You guys/girls have made amazing advances! I’m honored to learn from and help as much as my capabilities can. 

Thank you!

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Thanks! Wait you in slack :+1:

**Comment by ScriptedAlchemy** [comment]
@evilebottnawi i am unable to sign in, what email did you invite with / can you invite with

zack@scriptedalchemy.com

or my personal 

zackary.l.jackson@gmail.com

Sorry for inconvenience

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy please register in slack and send me your nickname to sheo13666q @ gmail.com

**Comment by ScriptedAlchemy** [comment]
when clicking your link, i get this screen...

I do however have my own slack `scriptedalchemy.slack.com`and the user is ScriptedAlchemy
fa3b03fa-907e-4105-8dc4-04d9d7b0c20d

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy some problems with slack, don't worry i will ping you :+1:

**Comment by ScriptedAlchemy** [comment]
Ahhh okay thank you. 

This is awesome!

**Comment by ScriptedAlchemy** [comment]
I know holidays are here. And you are busy as ever with your team! From being in open source, I know sometimes things get lost in the emails so will bump over the weekend @evilebottnawi

Have a good holiday season

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy I have not forgotten about you, don't worry i will ping you, some problem with permission to invite, WIP on this

**Comment by ScriptedAlchemy** [comment]
Ahh yeah thats okay! Let me know if you fellows need anything from me / more information about me for whatever reasons.

HAPPY HOLIDAYS as well!! Don’t forget to take some time with friends and family as new year approaches

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Thanks! Just some peoples who have permissions on `invite` now on holidays, so we need some wait, sorry for this, anyway feel free to start fixing issues :+1:

**Comment by ScriptedAlchemy** [comment]
I got the invite from Tobias! I’ll begin migrating and extract css into mini css. 

Hopefully some good feedback on better ways to implement the hot reloading solution:) I went on holiday as we were talking.  Up in mountains away from computers for the next week. But I’m excited to pitch in once back. 

Thanks again

**Pull request merged**
