### PR TITLE
Match webpack sourcemap relative paths

### LINKED ISSUE #1218: Sourcemaps from webpack & mini-css-extract-plugin have slightly different directory structure
# Bug report

**What is the current behavior?**
In webpack 5 w/ `mini-css-extract-plugin` and config `devtool: 'source-map'`, chrome groups css and js in different directories:
image

Here's the relevant snippet from the sourceMap files:
main.17fbf8.css.map: `"sources":["webpack://main/src/main.scss"]`
main.9c5261.js.map: `"sources":["webpack://main/./src/main.js"...`

[full webpack config](https://gist.github.com/isaacl/c933c48ccf4d893bee26c432bfcb2dd3)

It's annoying to have my files show separately in chrome, but I don't know which directory structure is more 'correct'. So, potentially, this is an issue for mini-css-extract-plugin.

**Other relevant information:**
webpack version:  5.3.2
Node.js version: v14.13.1
Operating System: OS X 10.15.7

---

This issue was moved from webpack/webpack#11910 by @evilebottnawi. Original issue was by @isaacl.

### PR DESCRIPTION
**Pull request by isaacl**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Adjust source path to match the way webpack generates sourcemaps
for js. This makes css and js sources appear in the same directory
when using sourcemaps in chrome.

Fixes #1218.

### Additional Info

### CODE REVIEW

**Comment by isaacl** [comment]
@evilebottnawi thanks for the tip

**Comment by evilebottnawi** [comment]
Yep, easy to fix, update snapshot too

**Comment by isaacl** [comment]
Is it not loading my snapshot changes?

**Comment by evilebottnawi** [comment]
Give me minute on fixing tests

**Comment by evilebottnawi** [comment]
Let's merge as is and I will fix tests in other PR, want to fix it ASAP

**Comment by isaacl** [comment]
I'm really confused by why the tests are failing, it seems like linux is getting a different contenthash than on my mac

**Comment by isaacl** [comment]
but previously they were both getting the same hash

**Comment by evilebottnawi** [comment]
hash is other because we should sources, so link on source maps changed also, so hash different, don't worry, all is fine

**Comment by isaacl** [comment]
I tried in #1221 but it still fails idk

**Pull request merged**
