### PR TITLE
Added extra example for url.filter for a common scenario

### PR DESCRIPTION
**Pull request by dovidweisz**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Provide an example for a common scenario (https://github.com/webpack/webpack/issues/15499).

I'm assuming this updates the docs at https://webpack.js.org/loaders/css-loader/#object-1. If this is not the case, please point me in the right direction.

### CODE REVIEW

**Comment by dovidweisz** [comment]
I rebased my changes to make the commit messages conform with the standard.

Are we able to run the checks again?

**Comment by alexander-akait** [comment]
Thanks!

**Comment by dovidweisz** [comment]
Cool

When with [the docs](https://webpack.js.org/loaders/css-loader/#object) get updated?

**Comment by alexander-akait** [comment]
In near future, we have bots for that

**Pull request merged**
