### PR TITLE
feat: allow `modules.getLocalIdent` to return a falsy value

### PR DESCRIPTION
**Pull request by ziir**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

With the suggested changes, `modules.getLocalIdent` would be allowed to return a falsy value, and in such case, the default `getLocalIdent` would be used instead.

I am setting up a new project with `webpack`, I wish to apply the same chain of loaders on different kinds of `.scss` files:
- `main.scss` specified as an `entry` in my configuration, meant to be used as global stylesheet
- `App.scss` SCSS modules which are imported from their matching component such as `App.js`

This setup works very well for me, except that `main.scss` classnames necessarily go through `css-loader` with `modules` enabled and using `localIdentName`.

See the following example:
```js
{
  test: /\.scss$/,
  loader: [
    MiniCSSExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1,
        modules: {
          localIdentName: '[name]-[local]__[hash:base64:5]',
        },
      },
    },
    {
      loader: 'sass-loader',
    },
  ],
},
```

While browsing issues, looking for a way to not use `localIdentName` for my `main.scss` file, I stumbled upon #862.
`getLocalIdent: () => foo && 'bar'` seemed to be a great fit for my use-case.
The behavior introduced in #865 wouldn't have worked for me though, here's what I did instinctively:
```js
modules: {
  localIdentName: '[name]-[local]__[hash:base64:5]',
  getLocalIdent: (context, localIdentName, localName) =>
    context.context.includes('shared/assets/styles') && localName,
},
```
Note: my `main.scss` file resides in `shared/assets/styles`.
This way, my SCSS modules will use `localIdentName` and `main.scss` will use `localName`.

### Breaking Changes

None

### Additional Info

Thank you for this great package :)
I'm willing to make the final changes if this looks reasonable, thank you in advance for any response.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA

**Comment by evilebottnawi** [comment]
Also need update https://github.com/webpack-contrib/css-loader/blob/master/src/options.json#L41 and add test

**Comment by ziir** [comment]
@evilebottnawi Thanks, signed the CLA.

I think I'm missing something, `localIdentName` remains a `string` and I cannot update `getLocalIdent` function return type?

I'm also not sure why some buils are failing.

**Comment by evilebottnawi** [comment]
i was wrong, need update snapshots `npm run test:only -- -u`

**Comment by ziir** [comment]
I already have updated the snapshots:
https://github.com/webpack-contrib/css-loader/pull/963/commits/bca916378eead10bc0a01952b27669da97414d7a#diff-3cb22b4647b22161352a612896f9eaa8

**Comment by evilebottnawi** [comment]
@ziir update `webpack` to latest version in `package.json` and `package-lock.json` and run updating again

**Comment by ziir** [comment]
@evilebottnawi thnx, all checks are green now :)

**Comment by evilebottnawi** [comment]
Thanks, release will be on next week (Monday i think)

**Pull request merged**
