### PR TITLE
refactor: rm `object-assign`

### PR DESCRIPTION
**Pull request by EsrefDurna**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the README?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by TrySound** [comment]
Can you also regenerate yarn.lock?

**Comment by EsrefDurna** [comment]
sure,

**Comment by EsrefDurna** [comment]
done by yarn upgrade

**Comment by michael-ciniawsky** [comment]
It's strictly viewed a semver major for the current code base, target is still node `>= v0.12` here. We need to estimate ecosystem (webpack v1.0.0) impact for this first (opinions).

**Comment by michael-ciniawsky** [comment]
Please also check your git email settings, if the email on github is different from the email you're using in your git config the CLA Bot will continue bug (falsely thinking there are two different commit authors)

**Comment by EsrefDurna** [comment]
Thanks for letting me know,

**Pull request closed without merging**
