### PR TITLE
chore(package): update `postcss` v5.0.6...v6.0.23 (`dependencies`)

### PR DESCRIPTION
**Pull request by mikeumus**
**What kind of change does this PR introduce?**

bugfix

**Summary**

Simple fix for #691

### CODE REVIEW

**Comment by mikeumus** [comment]
@evilebottnawi, what does that mean? Any changes from me? Would I have to get the tests passing for this new version of PostCSS?

**Comment by evilebottnawi** [comment]
@mikeumus css-loader works on any version node@js, but postcss only for 4 version, it is breaking change

**Comment by mikeumus** [comment]
@evilebottnawi, I see. Anything I can do on my end?

**Comment by evilebottnawi** [comment]
@mikeumus it is very big work :disappointed: first we should create new loader for css modules and remove this from default `css-loader`, you can start this

**Comment by mikeumus** [comment]
@evilebottnawi, I see, okay.

**Pull request closed without merging**
