### PR TITLE
Fix url relative path issue

### PR DESCRIPTION
**Pull request by inxi-pc**
Relate this issue. #338

The reg can optimize to suit more situation, i use `^\w` to solve `'test/xxx'` path,  hope guys can 

provide more suggestion.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@inxi-pc Please close and reopen the PR to trigger the CLA Bot again and rebase against current master. Also a test is missing, I'm not 💯 if this could break things, but in favour of the change in general 😛

**Comment by michael-ciniawsky** [comment]
@inxi-pc friendly ping 😛

**Comment by inxi-pc** [comment]
@michael-ciniawsky pong  😛...

**Comment by inxi-pc** [comment]
@michael-ciniawsky i forgot the point now..so long time ago..i close it just now!

**Comment by inxi-pc** [comment]
pls not

**Comment by inxi-pc** [comment]
@michael-ciniawsky CI failed, i dont know others if meet this issue, i suggest we close the pr only, when others meet same issue, then we reopen it and find the solution.

**Comment by kopax** [comment]
I have the same issue when trying to build in webpack tinymyce : 


```

ERROR in ./node_modules/tinymce/skins/lightgray/img/loader.gif
Module build failed: Error: spawn /usr/src/app/node_modules/gifsicle/vendor/gifsicle ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/css-loader!./node_modules/tinymce/skins/lightgray/skin.min.css 6:32349-32376
 @ ./node_modules/tinymce/skins/lightgray/skin.min.css
```

How did you guys solve it ?

**Pull request closed without merging**
