### PR TITLE
ci: remove install NPM steps

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

remove install NPM steps

### CODE REVIEW

**Comment by alexander-akait** [comment]
Regenerate lock file to fix security

**Comment by alexander-akait** [comment]
Still failed :disappointed:

**Comment by snitin315** [comment]
I am unable to run `npm audit fix`

Screenshot 2022-01-28 at 6 55 21 PM

**Comment by alexander-akait** [comment]
I will fix security problem :+1:

**Pull request merged**
