### PR TITLE
Remove minimize option

### PR DESCRIPTION
**Pull request by ai**
**What kind of change does this PR introduce?**

feature removing

**Did you add tests for your changes?**

tests were removed

**If relevant, did you update the README?**

docs were removed

**Summary**

@evilebottnawi suggested just to remove `minimize` option to fix problem with old Browserslist https://github.com/webpack-contrib/css-loader/pull/739

**Does this PR introduce a breaking change?**

yes

### CODE REVIEW

**Comment by ai** [comment]
Do we need something else for this PR? Or you just don’t want to release at the night?

**Comment by evilebottnawi** [comment]
> Or you just don’t want to release at the night?
yep

Also i remove some other options, I think tomorrow we will do release. I hope I will not be hated for this.

**Comment by shellscape** [comment]
For removing features we need very good documentation around _why_ this has to be done. Is this comment (https://github.com/webpack-contrib/css-loader/pull/739#issuecomment-402537380) the reason why this is being removed? If so, this PR's description should include that statement and also provide direction for users who look at this PR, for how to move to another loader for that feature.

**Comment by ai** [comment]
@shellscape you mean add love to ChangeLog?

**Comment by shellscape** [comment]
@ai changelog updates for breaking changes is required, yes. but PRs should have good info in them as well. I had to do some digging to find out why this PR was necessary, even with the link the PR description - users should not have to dig. Being verbose is good.

**Comment by ai** [comment]
Can I ask you to write docs? I am not native speaker.

**Comment by ai** [comment]
@shellscape what section in docs you recommend to describe changes? Seems like all previous changes was not described in docs. And we should just use ChangeLog.

@evilebottnawi can we accept it and write reasons in ChangeLog?

**Comment by evilebottnawi** [comment]
@ai I think you can close this PR if favor https://github.com/webpack-contrib/css-loader/pull/742, today i will do release

**Comment by ai** [comment]
@evilebottnawi are you plan to release 1.0 today?

**Comment by evilebottnawi** [comment]
@ai yes

**Comment by ai** [comment]
@evilebottnawi sure. I think it is better plan.

**Pull request closed without merging**
