### PR TITLE
fix: pass resolver to `localsLoader` (`options.alias`)

### LINKED ISSUE #602: [v0.28.6] TypeError: options.resolve is not a function
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The latest update breaks at processCss.js:88:27 with the titled error.

**If the current behavior is a bug, please provide the steps to reproduce.**
options.resolve not being provided to parserPlugin

### PR DESCRIPTION
**Pull request by liambuchanan**
### Issues

- Fixes #602 

> edited by @michael-ciniawsky (Formatting && Added Issue)

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
I'm not sure this is needed for `localsLoader`, what is your usecase? Could you give an example please ?

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - Ship it & i'll get this out

**Comment by liambuchanan** [comment]
sorry I disappeared for a while, thanks for dealing with this so quickly!

**Comment by d3viant0ne** [comment]
@liambuchanan - Available in [v0.28.7](https://github.com/webpack-contrib/css-loader/releases/tag/v0.28.7)

**Pull request merged**
