### PR TITLE
perf: change default localIdentName to [path]-[name]--[local]

### PR DESCRIPTION
**Pull request by enapupe**
**What kind of change does this PR introduce?**
refactoring/perf

**Did you add tests for your changes?**
I changed existing tests

**Summary**
Changes default `localIdentName` to `[path]-[name]--[local]` in order to save bytes when using gzip. For more context see #406 

**Does this PR introduce a breaking change?**
maybe❔ ❓ ❔ ❓

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@enapupe Thx, yep that's a breaking change and I'm not 💯  sure if it is guaranteed the every selector is unique tbh 😛 . Can someone verify ?

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - Can we as a general rule not ping Tobias, he's got his hands full. If we have a question on a PR that as a group we don't feel comfortable answering, we can ask him in slack.

**Comment by michael-ciniawsky** [comment]
Yep in general I'm not pinging him, but here I thought his opinion maybe valueable, but kk :)

**Comment by michael-ciniawsky** [comment]
@simlrh @evilebottnawi @bebraw @d3viant0ne Since we intend to remove CSS Modules from `css-loader` enterily in the next major and refactor them into a PostCSS Plugin used in conjunction with `postcss-loader` instead,  this either lands as minor with the slight risk of breaking things for some users or I need to close it. Could we triage the breakage risk of this again please and make a decision upon releasing as semver minor or not ?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky my opinion, be good close all issues about `css-modules` here and create repo `postcss-css-modules-loader-pack` (i really don't know best name :smile: ) and create todo (roadmap) with ref on this issues?

**Comment by michael-ciniawsky** [comment]
I create a repo for the PostCSS Modules Plugin && maybe for a prototype `cssm-loader` and give you full access to it until this evening (until tomorrow) so we can go all in 😛  and open 'umbrella' issues in `css-loader && postcss-loader`. But I still think it would be a good idea trying to work together with all included parts of this effort (`postcss-modules-*`, `*-loaders`) repos && authors and not release a new solution/package to lightly if otherwise solveable.

BTW do you have access to `postcss-loader` repo already ?  🙃

**Comment by evilebottnawi** [comment]
@michael-ciniawsky no, i don't access to any `loader`s :smile:

**Comment by michael-ciniawsky** [comment]
kk I will try to fix this soon

**Comment by michael-ciniawsky** [comment]
Closing since we don't intend to support CSS Modules in `css-loader` within the next major anymore, I will consider this as the default in `cssm-loader` instead. Thx 😛

**Pull request closed without merging**
