### PR TITLE
fix: remove restrictions: [/\.css$/i] from resolver configuration

### LINKED ISSUE #1164: Cannot @import "bar.scss" when the extension is not .css (4.0.0 regression)
`css-loader` ≥ 4.0.0 gives `Error: Can't resolve 'bar.scss'` when I try to `@import "bar.scss"`. It works when the extension is `.css` but not when it’s `.scss`. I bisected this to commit edf5347e4203a62e50b87248a83da198afdc6eba (#1099). The problem is triggered by the `restrictions: [/\.css$/i]` setting that was hard-coded here:

https://github.com/webpack-contrib/css-loader/blob/edf5347e4203a62e50b87248a83da198afdc6eba/src/index.js#L50-L56

- Operating System: NixOS 20.09
- Node Version: 14.7.0
- NPM Version: 6.14.7
- webpack Version: 4.44.1
- css-loader Version: 4.2.1

### Expected Behavior

With css-loader 3.6.0:

```console
$ npx webpack
Hash: 18aeb4131231a0da692b
Version: webpack 4.44.1
Time: 122ms
Built at: 08/12/2020 4:28:49 PM
  Asset      Size  Chunks             Chunk Names
main.js  8.05 KiB    main  [emitted]  main
Entrypoint main = main.js
[./foo.scss] 396 bytes {main} [built]
[./node_modules/css-loader/dist/cjs.js!./bar.scss] 278 bytes {main} [built]
    + 1 hidden module
Done in 0.46s.
```

### Actual Behavior

With css-loader ≥ 4.0.0:

```console
$ npx webpack 
Hash: 8a377e383c6ebf971c58
Version: webpack 4.44.1
Time: 120ms
Built at: 08/12/2020 4:30:02 PM
  Asset      Size  Chunks             Chunk Names
main.js  6.36 KiB    main  [emitted]  main
Entrypoint main = main.js
[./foo.scss] 2.58 KiB {main} [built] [failed] [1 error]

ERROR in ./foo.scss
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'bar.scss' in '/tmp/b'
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/b/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /tmp/b/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
```

### Code

```js
// webpack.config.js
module.exports = {
  mode: "development",
  entry: "./foo.scss",
  module: {
    rules: [{ test: /\.s?css$/, use: "css-loader" }],
  },
};
```

```css
/* foo.scss */
@import "bar.scss"
```

```css
/* bar.scss */
html {
  background: red;
}
```

### How Do We Reproduce?

Create the three files above and run `npm i webpack webpack-cli css-loader; npx webpack`.

### PR DESCRIPTION
**Pull request by andersk**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #1164.

### CODE REVIEW

**Review by busymaster55 — APPROVED** [review]

**Comment by Cryszon** [comment]
> It is break other resolutions, no you can import even `JS` file

I'm using PostCSS, but cannot currently use `.pcss` extension with this loader. The reason for using `.pcss` instead of `.css` is for VS Code to detect the language automatically and display correct syntax highlighting.

I can understand not allowing `.js` or `.scss` imports (although I personally think it should be the developers responsibility to ensure correct import extensions), but do you have any suggestions on how to handle PostCSS files?

**Comment by alexander-akait** [comment]
Why you need `pcss`? You can convert them using `postcss-loader` to CSS, this problem signals that you forgot to convert to CSS, pcss can contains invalid CSS syntax

**Comment by Cryszon** [comment]
Here's a snippet of my Webpack configuration for CSS:
```
      {
        test: /\.(p?css)$/,
        use: [
          { loader: MiniCssExtractPlugin.loader },
          { loader: "css-loader", options: { importLoaders: 1 } },
          "postcss-loader",
        ],
      },
```

And here's my `postcss.config.js`
```
const tailwindcss = require("tailwindcss");
const postcssPresetEnv = require("postcss-preset-env");

var config = ({ file, options, env }) => ({
  plugins: [
    tailwindcss,
    postcssPresetEnv({
      stage: 1,
    }),
  ],
});

module.exports = config;
```

Is there something I need to do to make PostCSS handle imports before `css-loader`

**Comment by alexander-akait** [comment]
Here interesting problem, why it is hard to fix - some packages contain `package.json` with `"main": "style.css"` other `"main": "main.js"`, so we need specify `restrictions`, otherwise we will get `js` file, if we remove it we will break compatibility with some packages, why it happen, because npm doesn't provide field to specify `styles` a long time ago, but now we have `exports` (condition names) and ideally package should migrate on it in future.

We are standing on a very shaky board - break compatibility with packages or allow to use non standard extensions in imports

**Comment by andersk** [comment]
This change will not cause anyone to get a `.js` file when they previously would have gotten a `.css` file (because it removes `restrictions`, not `extensions`). If a package specifies `"main": "main.js"`, then it does not work with `@import` and there is no compatibility to break.

**Comment by alexander-akait** [comment]
`extensions` is not affected on `main`, because it is different things

**Comment by alexander-akait** [comment]
Ideally `extensions` should be `[]` here, because we allow to use `import 'index'` (where `index.css`)

**Comment by alexander-akait** [comment]
> If a package foo specifies "main": "main.js", then @import "~foo" has never worked and there is no compatibility to break.

Some packages can contains `"main": "style.css"` and  `style: "style.scss"`, so when you use `@import 'package';` we will get `sass` not `css`

**Comment by alexander-akait** [comment]
But maybe we should start to say developers do not use `main` for `CSS` files and remove this restriction

**Pull request closed without merging**
