### PR TITLE
build!: minimum supported Nodejs version is 14.15.0

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Update Nodejs

### Breaking Changes

minimum supported Nodejs version is 14.15.0

### Additional Info
Let's update dependencies separate.

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Good job, I think we have some TODOs here, do you want to help me solve them?

**Comment by snitin315** [comment]
@alexander-akait sure, let me know about them. Also, can we directly merge this into master?

**Comment by alexander-akait** [comment]
Let's look how many issuea we have, maybe we can do it just in couple PRs and we will merge them together or I can merge them into the next branch, dependes how you prefer

**Comment by snitin315** [comment]
@alexander-akait let's use the `next-v7` branch.

**Comment by alexander-akait** [comment]
:+1:

**Pull request merged**
