### PR TITLE
fix: correct plugin order for CSS Modules

### LINKED ISSUE #533: CSS Modules: error when composing imported class
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Error when composing imported class.

**If the current behavior is a bug, please provide the steps to reproduce.**
``` css
@value colors: './colors.css';

.foo {
    composes: text from colors;
}
```

``` css
/* colors.css */
.text {
    color: yellow;
}
```

webpack config:

```
module.exports = {
    entry: './src/main.css',
    output: {
        filename: './target/main.css',
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                        },
                    },
                ]
            }
        ]
    }
}
```

Gives error:

```
ERROR in ./~/css-loader?{"modules":true}!./src/main.css
Module build failed: referenced class name "text" in composes not found (4:5)

  2 |
  3 | .foo {
> 4 |     composes: text from colors;
    |     ^
  5 | }
  6 |
```

Full test case at https://github.com/OliverJAsh/postcss-modules-values-test. After cloning:
```
yarn
webpack
```

**What is the expected behavior?**
No error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack 2.5.1
css-loader 0.28.1

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes #533

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@OliverJAsh We are preparing for release `css-loader` `v1`, new version don't support `css-modules`. If your want work with `css-modules` best use `postcss-loader` with `postcss-modules`(https://github.com/css-modules/postcss-modules). Also your can help our with https://github.com/postcss/postcss-loader/issues/227. 

Now we accept only critical bug fixes for `css-loader`.

**Comment by evilebottnawi** [comment]
@OliverJAsh new loader will be support only `icss` spec (https://github.com/css-modules/icss)

**Comment by michael-ciniawsky** [comment]
@OliverJAsh Did you test this change with a larger code base for breaking changes, it eventually isn't breaking and could go as a semver minor

**Comment by OliverJAsh** [comment]
I have only tested against one large code base. Others may like to try it out

**Comment by TrySound** [comment]
@michael-ciniawsky Not quite independent :)

**Comment by michael-ciniawsky** [comment]
These may need a short handwritten note in the release notes, to be aware of edge cases otherwise I respond to eventual issues :)

**Comment by michael-ciniawsky** [comment]
@OliverJAsh Thx

**Comment by OliverJAsh** [comment]
Great, thanks! When will this be released, do you know?

**Comment by d3viant0ne** [comment]
Right about now - https://github.com/webpack-contrib/css-loader/blob/v0.28.3/CHANGELOG.md#0283-2017-05-25

**Pull request merged**
