### PR TITLE
chore(package): update `source-list-map v0.1.7...2.0.0` (`dependencies`)

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**

not required

**If relevant, did you update the README?**

not required

**Summary**

Just update deps

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by TrySound** [comment]
Don't update icss-utils. It comes with new behavior (selectors replacing) which may introduce some bugs because of plugins incompatibility.

**Comment by evilebottnawi** [comment]
@TrySound v2 doesn't have this bugs?

**Comment by TrySound** [comment]
@evilebottnawi It's not bugs. This behavior is not used in old plugins. And such replacements can happend in unexpected way.

**Comment by michael-ciniawsky** [comment]
@TrySound Offtopic: Can we update all `postcss-modules-*` to the latest version (PostCSS 6 Support) as a semver minor for the loader (final minor update, I start with `new-loader` as soon as possible). It's a separate PR though, but to clarify... 😛

**Comment by TrySound** [comment]
@michael-ciniawsky Sure. I first did update with no extra changes.

**Pull request merged**
